In [95]:
import pandas as pd
import numpy as np

In [96]:
nykaa_df=pd.read_csv(r"C:\Users\sindh\OneDrive\Documents\Data science GUVI\Project 3 - Marketing campaign\nykaa_campaign_data_with_nulls.csv")
nykaa_df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21.0,"WhatsApp, YouTube",57804.0,6156.0,3616.0,2355.0,1867515.0,NaN,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.0,YouTube,91801.0,3321.0,1971.0,1357.0,1046247.0,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23.0,"WhatsApp, Google, YouTube",15536.0,2182.0,952.0,755.0,197055.0,90.60,NaN,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18.0,"YouTube, Facebook, Instagram",88114.0,8413.0,2231.0,947.0,376906.0,249.07,0.60,Hindi,13.15,NaN,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10.0,"Facebook, Instagram",96871.0,3743.0,2060.0,1258.0,518296.0,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NY-CMP-56550,SEO,Youth,16.0,"Instagram, Email",31041.0,3849.0,1012.0,639.0,162945.0,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,16-02-2025
55551,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26.0,Facebook,27335.0,3715.0,2184.0,1006.0,792728.0,56.38,12.98,English,25.26,Premium Shoppers,18-11-2024
55552,NY-CMP-56552,Influencer,Tier 2 City Customers,23.0,NaN,43481.0,6447.0,3751.0,1668.0,383640.0,56.18,3.09,Bengali,27.29,Working Women,24-10-2024
55553,NY-CMP-56553,Social Media,College Students,16.0,"Facebook, Email",NaN,2518.0,584.0,299.0,194051.0,227.53,1.85,Bengali,10.14,Working Women,22-05-2025
55554,NY-CMP-56554,Social Media,College Students,25.0,"YouTube, Instagram, WhatsApp",41096.0,5254.0,2570.0,1894.0,647748.0,35.11,8.74,English,23.65,College Students,30-05-2025

In [97]:
purplle_df=pd.read_csv(r"C:\Users\sindh\OneDrive\Documents\Data science GUVI\Project 3 - Marketing campaign\purplle_campaign_data_with_nulls.csv")
purplle_df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,PU-CMP-1000,Paid Ads,Working Women,6.0,"Facebook, Google",31869.0,3490.0,1946.0,902.0,493394.0,55.93,8.78,Tamil,19.89,Premium Shoppers,27-12-2024
1,PU-CMP-1001,Paid Ads,Premium Shoppers,8.0,"Instagram, WhatsApp",26640.0,2441.0,741.0,314.0,108644.0,197.44,0.75,Bengali,13.12,NaN,26-11-2024
2,PU-CMP-1002,Influencer,Youth,22.0,"Facebook, WhatsApp",36967.0,4997.0,1025.0,653.0,NaN,234.59,0.56,NaN,18.06,College Students,08-01-2025
3,PU-CMP-1003,Paid Ads,Youth,15.0,"Instagram, WhatsApp",73258.0,5893.0,2565.0,1970.0,1341570.0,103.76,5.56,Bengali,14.23,College Students,14-03-2025
4,PU-CMP-1004,Social Media,Premium Shoppers,11.0,"WhatsApp, Instagram",91081.0,6393.0,3282.0,2582.0,787510.0,78.61,NaN,English,13.46,College Students,11-07-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,PU-CMP-56550,SEO,Premium Shoppers,10.0,"WhatsApp, Instagram",58191.0,7763.0,3471.0,2132.0,1097980.0,73.52,6.00,Tamil,22.97,Youth,08-05-2025
55551,PU-CMP-56551,Email,Tier 2 City Customers,12.0,"YouTube, Google",85085.0,8986.0,4096.0,2308.0,800876.0,53.17,5.53,Tamil,18.09,College Students,23-08-2024
55552,PU-CMP-56552,Email,College Students,29.0,"YouTube, Google, Email",66094.0,4051.0,2155.0,1307.0,414319.0,113.10,1.80,Bengali,NaN,NaN,09-11-2024
55553,PU-CMP-56553,Paid Ads,College Students,7.0,"Facebook, WhatsApp",65050.0,5196.0,2263.0,1235.0,737295.0,237.80,NaN,Hindi,13.37,Youth,30-09-2024
55554,PU-CMP-56554,Social Media,College Students,25.0,"Facebook, Instagram, Email",19137.0,1529.0,512.0,303.0,154227.0,252.94,1.01,Hindi,12.25,Premium Shoppers,04-11-2024

In [98]:
tira_df=pd.read_csv(r"C:\Users\sindh\OneDrive\Documents\Data science GUVI\Project 3 - Marketing campaign\tira_campaign_data_with_nulls.csv")
tira_df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,TI-CMP-1000,SEO,Working Women,11.0,NaN,64004.0,2906.0,1639.0,952.0,222768.0,129.72,0.80,Tamil,NaN,Premium Shoppers,30-10-2024
1,TI-CMP-1001,Social Media,Tier 2 City Customers,24.0,YouTube,71795.0,2051.0,552.0,256.0,199168.0,316.36,1.46,Tamil,3.98,College Students,11-09-2024
2,TI-CMP-1002,NaN,Working Women,28.0,NaN,79158.0,3546.0,1928.0,1314.0,433620.0,NaN,2.62,English,8.58,Tier 2 City Customers,28-08-2024
3,TI-CMP-1003,Email,Youth,8.0,Google,31523.0,3721.0,2088.0,736.0,571872.0,161.13,3.82,Bengali,20.76,Youth,27-07-2024
4,TI-CMP-1004,Paid Ads,Premium Shoppers,15.0,"Facebook, Email, WhatsApp",61441.0,7277.0,3615.0,2602.0,1477936.0,82.07,NaN,Tamil,21.96,College Students,19-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NaN,NaN,Tier 2 City Customers,11.0,"Instagram, YouTube, Email",NaN,3799.0,NaN,1099.0,454986.0,213.21,0.94,Bengali,10.70,Youth,12-11-2024
55551,TI-CMP-56551,SEO,Working Women,20.0,"Google, Instagram",54886.0,1578.0,634.0,NaN,136514.0,436.24,-0.09,English,4.66,Working Women,25-08-2024
55552,TI-CMP-56552,Email,NaN,13.0,"Facebook, Instagram",97954.0,11480.0,4567.0,2144.0,445952.0,78.77,1.64,NaN,18.57,Premium Shoppers,15-04-2025
55553,NaN,Influencer,Premium Shoppers,22.0,"Google, Email",11669.0,NaN,122.0,44.0,26884.0,NaN,-0.76,English,5.35,Working Women,21-07-2024
55554,TI-CMP-56554,Paid Ads,Working Women,NaN,Instagram,50497.0,1604.0,542.0,363.0,281688.0,151.44,4.12,English,4.97,Premium Shoppers,02-05-2025

In [99]:
tira_df["Brand_name"]="Tira"
purplle_df["Brand_name"]="Purplle"
nykaa_df["Brand_name"]="Nykaa"

In [100]:
tira_df.columns

Index(['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Duration',
       'Channel_Used', 'Impressions', 'Clicks', 'Leads', 'Conversions',
       'Revenue', 'Acquisition_Cost', 'ROI', 'Language', 'Engagement_Score',
       'Customer_Segment', 'Date', 'Brand_name'],
      dtype='str')

In [101]:
print("Brand_name" in tira_df.columns)
print(tira_df.columns.tolist())

True
['Campaign_ID', 'Campaign_Type', 'Target_Audience', 'Duration', 'Channel_Used', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Revenue', 'Acquisition_Cost', 'ROI', 'Language', 'Engagement_Score', 'Customer_Segment', 'Date', 'Brand_name']

In [102]:
print(tira_df.columns.equals(purplle_df.columns))
print(tira_df.columns.equals(nykaa_df.columns))

True
True

In [103]:
print(tira_df.dtypes)
print("*******")
print(purplle_df.dtypes)
print("*******")
print(nykaa_df.dtypes)

Campaign_ID             str
Campaign_Type           str
Target_Audience         str
Duration            float64
Channel_Used            str
Impressions         float64
Clicks              float64
Leads               float64
Conversions         float64
Revenue             float64
Acquisition_Cost    float64
ROI                 float64
Language                str
Engagement_Score    float64
Customer_Segment        str
Date                    str
Brand_name              str
dtype: object
*******
Campaign_ID             str
Campaign_Type           str
Target_Audience         str
Duration            float64
Channel_Used            str
Impressions         float64
Clicks              float64
Leads               float64
Conversions         float64
Revenue             float64
Acquisition_Cost    float64
ROI                 float64
Language                str
Engagement_Score    float64
Customer_Segment        str
Date                    str
Brand_name              str
dtype: object
*******
Campaign_ID             str
Campaign_Type           str
Target_Audience         str
Duration            float64
Channel_Used            str
Impressions         float64
Clicks              float64
Leads               float64
Conversions         float64
Revenue             float64
Acquisition_Cost    float64
ROI                 float64
Language                str
Engagement_Score    float64
Customer_Segment        str
Date                    str
Brand_name              str
dtype: object

In [104]:
tira_df['Date'] = pd.to_datetime(tira_df['Date'], format='%d-%m-%Y')
purplle_df['Date'] = pd.to_datetime(purplle_df['Date'], format='%d-%m-%Y')
nykaa_df['Date'] = pd.to_datetime(nykaa_df['Date'], format='%d-%m-%Y')

In [105]:
str_cols = tira_df.select_dtypes(include=['string']).columns
tira_df[str_cols] = tira_df[str_cols].fillna(pd.NA)
str_cols = purplle_df.select_dtypes(include=['string']).columns
purplle_df[str_cols] = purplle_df[str_cols].fillna(pd.NA)
str_cols = nykaa_df.select_dtypes(include=['string']).columns
nykaa_df[str_cols] = nykaa_df[str_cols].fillna(pd.NA)

In [106]:
tira_df.head(3)

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date,Brand_name
0,TI-CMP-1000,SEO,Working Women,11.0,NaN,64004.0,2906.0,1639.0,952.0,222768.0,129.72,0.80,Tamil,NaN,Premium Shoppers,2024-10-30,Tira
1,TI-CMP-1001,Social Media,Tier 2 City Customers,24.0,YouTube,71795.0,2051.0,552.0,256.0,199168.0,316.36,1.46,Tamil,3.98,College Students,2024-09-11,Tira
2,TI-CMP-1002,NaN,Working Women,28.0,NaN,79158.0,3546.0,1928.0,1314.0,433620.0,NaN,2.62,English,8.58,Tier 2 City Customers,2024-08-28,Tira

In [107]:
tira_df[tira_df.duplicated()]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date, Brand_name]
Index: []

In [108]:
nykaa_df[nykaa_df.duplicated()]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date, Brand_name]
Index: []

In [109]:
purplle_df[purplle_df.duplicated()]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date, Brand_name]
Index: []

In [110]:
tira_df[tira_df.isna().all(axis=1)]
nykaa_df[nykaa_df.isna().all(axis=1)]
purplle_df[purplle_df.isna().all(axis=1)]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date, Brand_name]
Index: []

In [111]:
tira_df.isna().sum()

Campaign_ID         2733
Campaign_Type       2709
Target_Audience     2664
Duration            2665
Channel_Used        2733
Impressions         2723
Clicks              2730
Leads               2657
Conversions         2660
Revenue             2729
Acquisition_Cost    2650
ROI                 2742
Language            2786
Engagement_Score    2730
Customer_Segment    2711
Date                2690
Brand_name             0
dtype: int64

In [112]:
null_percentage = ((tira_df.isna().sum() / len(tira_df)) * 100).round(2)
print(null_percentage.sort_values(ascending=False))

Language            5.01
ROI                 4.94
Campaign_ID         4.92
Channel_Used        4.92
Clicks              4.91
Engagement_Score    4.91
Revenue             4.91
Impressions         4.90
Campaign_Type       4.88
Customer_Segment    4.88
Date                4.84
Target_Audience     4.80
Duration            4.80
Conversions         4.79
Leads               4.78
Acquisition_Cost    4.77
Brand_name          0.00
dtype: float64

In [113]:
purplle_df.isna().sum()

Campaign_ID         2684
Campaign_Type       2790
Target_Audience     2747
Duration            2768
Channel_Used        2744
Impressions         2721
Clicks              2712
Leads               2654
Conversions         2674
Revenue             2763
Acquisition_Cost    2698
ROI                 2731
Language            2745
Engagement_Score    2602
Customer_Segment    2676
Date                2651
Brand_name             0
dtype: int64

In [114]:
nykaa_df.isna().sum()

Campaign_ID            0
Campaign_Type       2859
Target_Audience     2761
Duration            2890
Channel_Used        2805
Impressions         2780
Clicks              2782
Leads               2779
Conversions         2666
Revenue             2812
Acquisition_Cost    2813
ROI                 2825
Language            2768
Engagement_Score    2749
Customer_Segment    2788
Date                2758
Brand_name             0
dtype: int64

In [115]:
tira_df['ROI'] = tira_df['ROI'].fillna(0)
purplle_df['ROI']=purplle_df['ROI'].fillna(0)
nykaa_df['ROI']=nykaa_df['ROI'].fillna(0)

tira_df = tira_df.fillna(
    tira_df.select_dtypes(include='number').mean()
)
nykaa_df = nykaa_df.fillna(
    nykaa_df.select_dtypes(include='number').mean()
)
purplle_df = purplle_df.fillna(
    purplle_df.select_dtypes(include='number').mean()
)

In [116]:
final_df = pd.concat(
    [tira_df, purplle_df, nykaa_df],
    ignore_index=True
)
final_df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date,Brand_name
0,TI-CMP-1000,SEO,Working Women,11.0,NaN,64004.000000,2906.0,1639.0,952.0,222768.0,129.720000,0.80,Tamil,13.756235,Premium Shoppers,2024-10-30,Tira
1,TI-CMP-1001,Social Media,Tier 2 City Customers,24.0,YouTube,71795.000000,2051.0,552.0,256.0,199168.0,316.360000,1.46,Tamil,3.980000,College Students,2024-09-11,Tira
2,TI-CMP-1002,NaN,Working Women,28.0,NaN,79158.000000,3546.0,1928.0,1314.0,433620.0,374.920868,2.62,English,8.580000,Tier 2 City Customers,2024-08-28,Tira
3,TI-CMP-1003,Email,Youth,8.0,Google,31523.000000,3721.0,2088.0,736.0,571872.0,161.130000,3.82,Bengali,20.760000,Youth,2024-07-27,Tira
4,TI-CMP-1004,Paid Ads,Premium Shoppers,15.0,"Facebook, Email, WhatsApp",61441.000000,7277.0,3615.0,2602.0,1477936.0,82.070000,0.00,Tamil,21.960000,College Students,2024-12-19,Tira
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166660,NY-CMP-56550,SEO,Youth,16.0,"Instagram, Email",31041.000000,3849.0,1012.0,639.0,162945.0,374.900000,-0.32,Tamil,17.720000,Tier 2 City Customers,2025-02-16,Nykaa
166661,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26.0,Facebook,27335.000000,3715.0,2184.0,1006.0,792728.0,56.380000,12.98,English,25.260000,Premium Shoppers,2024-11-18,Nykaa
166662,NY-CMP-56552,Influencer,Tier 2 City Customers,23.0,NaN,43481.000000,6447.0,3751.0,1668.0,383640.0,56.180000,3.09,Bengali,27.290000,Working Women,2024-10-24,Nykaa
166663,NY-CMP-56553,Social Media,College Students,16.0,"Facebook, Email",55119.386698,2518.0,584.0,299.0,194051.0,227.530000,1.85,Bengali,10.140000,Working Women,2025-05-22,Nykaa
166664,NY-CMP-56554,Social Media,College Students,25.0,"YouTube, Instagram, WhatsApp",41096.000000,5254.0,2570.0,1894.0,647748.0,35.110000,8.74,English,23.650000,College Students,2025-05-30,Nykaa

In [117]:
print(final_df["Brand_name"].value_counts())

Brand_name
Tira       55555
Purplle    55555
Nykaa      55555
Name: count, dtype: int64

In [118]:
print(final_df["Channel_Used"].value_counts())

Channel_Used
Email                           8953
Instagram                       8858
Facebook                        8791
Google                          8740
WhatsApp                        8705
                                ...
Google, YouTube, Email           398
Email, YouTube, Instagram        390
Instagram, Facebook, YouTube     390
Email, Google, YouTube           390
Email, YouTube, Facebook         389
Name: count, Length: 156, dtype: int64

In [119]:
for value in final_df["Channel_Used"].unique():
    print(repr(value))

nan
'YouTube'
'Google'
'Facebook, Email, WhatsApp'
'Google, Facebook'
'Email, YouTube, WhatsApp'
'Google, Facebook, Instagram'
'Email, WhatsApp, Facebook'
'WhatsApp'
'YouTube, Google'
'YouTube, Instagram, Facebook'
'WhatsApp, YouTube, Facebook'
'Facebook'
'Instagram'
'Instagram, Email, Google'
'YouTube, Email, Google'
'Facebook, Instagram, WhatsApp'
'WhatsApp, Instagram'
'Email, Google'
'Email, YouTube, Instagram'
'WhatsApp, Facebook, Instagram'
'Instagram, WhatsApp, Google'
'Email'
'Instagram, WhatsApp, YouTube'
'Google, WhatsApp, Instagram'
'WhatsApp, Email'
'Google, WhatsApp'
'Email, Facebook'
'YouTube, Instagram, WhatsApp'
'YouTube, WhatsApp, Email'
'Email, Instagram'
'YouTube, WhatsApp, Instagram'
'Instagram, Email, YouTube'
'Email, YouTube'
'Email, Instagram, YouTube'
'Facebook, YouTube'
'Google, Email'
'Email, YouTube, Google'
'Google, YouTube'
'YouTube, Instagram'
'YouTube, Facebook'
'Instagram, YouTube, Email'
'Facebook, Instagram'
'Instagram, WhatsApp'
'YouTube, Google, Email'
'Instagram, YouTube, Facebook'
'Google, Facebook, WhatsApp'
'Instagram, Google, Email'
'WhatsApp, YouTube'
'Facebook, Google'
'Instagram, Google'
'Email, Google, Facebook'
'Google, Instagram'
'YouTube, WhatsApp, Google'
'Google, Email, YouTube'
'YouTube, Instagram, Email'
'Google, YouTube, WhatsApp'
'Facebook, WhatsApp'
'WhatsApp, Instagram, Google'
'Instagram, YouTube'
'WhatsApp, Email, YouTube'
'YouTube, Google, Instagram'
'Google, WhatsApp, Facebook'
'Instagram, Email'
'Email, Google, Instagram'
'Instagram, Facebook'
'WhatsApp, Email, Facebook'
'Instagram, Facebook, WhatsApp'
'WhatsApp, Facebook, Google'
'Email, Facebook, WhatsApp'
'YouTube, WhatsApp, Facebook'
'YouTube, Instagram, Google'
'Email, Instagram, WhatsApp'
'Google, Instagram, WhatsApp'
'YouTube, Google, WhatsApp'
'Google, Email, Instagram'
'Google, YouTube, Email'
'Google, WhatsApp, YouTube'
'Facebook, YouTube, Instagram'
'Facebook, Google, YouTube'
'Google, Instagram, Email'
'Google, YouTube, Instagram'
'WhatsApp, Email, Instagram'
'WhatsApp, Email, Google'
'Facebook, WhatsApp, YouTube'
'YouTube, Email, WhatsApp'
'Email, WhatsApp'
'YouTube, Email, Instagram'
'Email, YouTube, Facebook'
'YouTube, Facebook, Instagram'
'YouTube, Email'
'Email, Facebook, YouTube'
'WhatsApp, Google, Instagram'
'Facebook, Email'
'YouTube, Google, Facebook'
'Facebook, Google, WhatsApp'
'WhatsApp, Google, Email'
'YouTube, Facebook, Email'
'Google, Facebook, YouTube'
'Instagram, YouTube, WhatsApp'
'Email, Instagram, Facebook'
'Email, WhatsApp, Instagram'
'Facebook, YouTube, Email'
'Instagram, Email, WhatsApp'
'Instagram, WhatsApp, Email'
'Facebook, WhatsApp, Google'
'WhatsApp, Google, YouTube'
'WhatsApp, YouTube, Instagram'
'YouTube, WhatsApp'
'Facebook, Email, YouTube'
'WhatsApp, Facebook, YouTube'
'YouTube, Email, Facebook'
'Google, Facebook, Email'
'Facebook, WhatsApp, Instagram'
'Instagram, Facebook, YouTube'
'WhatsApp, Google, Facebook'
'WhatsApp, YouTube, Google'
'Instagram, Facebook, Email'
'Facebook, Instagram, YouTube'
'Facebook, Google, Instagram'
'Facebook, Email, Instagram'
'WhatsApp, Google'
'WhatsApp, Facebook'
'Google, YouTube, Facebook'
'Instagram, Email, Facebook'
'Email, Google, YouTube'
'Facebook, Email, Google'
'YouTube, Facebook, WhatsApp'
'Instagram, WhatsApp, Facebook'
'Instagram, Google, YouTube'
'Instagram, YouTube, Google'
'WhatsApp, Instagram, Facebook'
'WhatsApp, YouTube, Email'
'WhatsApp, Instagram, Email'
'Email, WhatsApp, YouTube'
'Facebook, Instagram, Email'
'YouTube, Facebook, Google'
'Facebook, YouTube, Google'
'Email, WhatsApp, Google'
'Facebook, Instagram, Google'
'Facebook, WhatsApp, Email'
'Email, Google, WhatsApp'
'WhatsApp, Instagram, YouTube'
'WhatsApp, Facebook, Email'
'Email, Facebook, Google'
'Google, WhatsApp, Email'
'Google, Instagram, YouTube'
'Google, Instagram, Facebook'
'Instagram, Google, WhatsApp'
'Instagram, Facebook, Google'
'Email, Instagram, Google'
'Facebook, Google, Email'
'Email, Facebook, Instagram'
'Instagram, Google, Facebook'
'Google, Email, WhatsApp'
'Facebook, YouTube, WhatsApp'
'Google, Email, Facebook'

In [120]:
for value in final_df["Language"].unique():
    print(repr(value))

'Tamil'
'English'
'Bengali'
'Hindi'
nan

In [121]:
for value in final_df["Target_Audience"].unique():
    print(repr(value))

'Working Women'
'Tier 2 City Customers'
'Youth'
'Premium Shoppers'
'College Students'
nan

In [122]:
final_df['Calculated_ROI'] = (
    (final_df['Revenue'] - final_df['Acquisition_Cost']) / final_df['Acquisition_Cost']
)

In [123]:
final_df[final_df['Calculated_ROI']-final_df['ROI']>0]

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date,Brand_name,Calculated_ROI
0,TI-CMP-1000,SEO,Working Women,11.0,NaN,64004.000000,2906.0,1639.0,952.0,222768.0,129.720000,0.80,Tamil,13.756235,Premium Shoppers,2024-10-30,Tira,1716.298797
1,TI-CMP-1001,Social Media,Tier 2 City Customers,24.0,YouTube,71795.000000,2051.0,552.0,256.0,199168.0,316.360000,1.46,Tamil,3.980000,College Students,2024-09-11,Tira,628.561259
2,TI-CMP-1002,NaN,Working Women,28.0,NaN,79158.000000,3546.0,1928.0,1314.0,433620.0,374.920868,2.62,English,8.580000,Tier 2 City Customers,2024-08-28,Tira,1155.564057
3,TI-CMP-1003,Email,Youth,8.0,Google,31523.000000,3721.0,2088.0,736.0,571872.0,161.130000,3.82,Bengali,20.760000,Youth,2024-07-27,Tira,3548.134239
4,TI-CMP-1004,Paid Ads,Premium Shoppers,15.0,"Facebook, Email, WhatsApp",61441.000000,7277.0,3615.0,2602.0,1477936.0,82.070000,0.00,Tamil,21.960000,College Students,2024-12-19,Tira,18007.236871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166660,NY-CMP-56550,SEO,Youth,16.0,"Instagram, Email",31041.000000,3849.0,1012.0,639.0,162945.0,374.900000,-0.32,Tamil,17.720000,Tier 2 City Customers,2025-02-16,Nykaa,433.635903
166661,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26.0,Facebook,27335.000000,3715.0,2184.0,1006.0,792728.0,56.380000,12.98,English,25.260000,Premium Shoppers,2024-11-18,Nykaa,14059.446967
166662,NY-CMP-56552,Influencer,Tier 2 City Customers,23.0,NaN,43481.000000,6447.0,3751.0,1668.0,383640.0,56.180000,3.09,Bengali,27.290000,Working Women,2024-10-24,Nykaa,6827.764685
166663,NY-CMP-56553,Social Media,College Students,16.0,"Facebook, Email",55119.386698,2518.0,584.0,299.0,194051.0,227.530000,1.85,Bengali,10.140000,Working Women,2025-05-22,Nykaa,851.858964
166664,NY-CMP-56554,Social Media,College Students,25.0,"YouTube, Instagram, WhatsApp",41096.000000,5254.0,2570.0,1894.0,647748.0,35.110000,8.74,English,23.650000,College Students,2025-05-30,Nykaa,18448.102820

In [124]:
final_df = final_df.drop(columns=['ROI'])

In [125]:
final_df.rename(columns={'Calculated_ROI': 'ROI'}, inplace=True)

In [126]:
final_df.head(3)

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,Language,Engagement_Score,Customer_Segment,Date,Brand_name,ROI
0,TI-CMP-1000,SEO,Working Women,11.0,NaN,64004.0,2906.0,1639.0,952.0,222768.0,129.720000,Tamil,13.756235,Premium Shoppers,2024-10-30,Tira,1716.298797
1,TI-CMP-1001,Social Media,Tier 2 City Customers,24.0,YouTube,71795.0,2051.0,552.0,256.0,199168.0,316.360000,Tamil,3.980000,College Students,2024-09-11,Tira,628.561259
2,TI-CMP-1002,NaN,Working Women,28.0,NaN,79158.0,3546.0,1928.0,1314.0,433620.0,374.920868,English,8.580000,Tier 2 City Customers,2024-08-28,Tira,1155.564057

In [127]:
    final_df['Profit_Loss'] = final_df['ROI'].apply(
        lambda x: 'Profit' if x > 0 else 'Loss'
    )

In [128]:
(final_df['ROI'] < 0).sum()

np.int64(11)

In [129]:
df_all=final_df.copy()

In [130]:
df_all.to_csv("df_all.csv", index=False)

In [131]:
channel_dummies = final_df['Channel_Used'].str.get_dummies(sep=', ')

final_df = pd.concat([final_df.drop('Channel_Used', axis=1),
                channel_dummies],
               axis=1)

In [132]:
final_df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,...,Date,Brand_name,ROI,Profit_Loss,Email,Facebook,Google,Instagram,WhatsApp,YouTube
0,TI-CMP-1000,SEO,Working Women,11.0,64004.000000,2906.0,1639.0,952.0,222768.0,129.720000,...,2024-10-30,Tira,1716.298797,Profit,0,0,0,0,0,0
1,TI-CMP-1001,Social Media,Tier 2 City Customers,24.0,71795.000000,2051.0,552.0,256.0,199168.0,316.360000,...,2024-09-11,Tira,628.561259,Profit,0,0,0,0,0,1
2,TI-CMP-1002,NaN,Working Women,28.0,79158.000000,3546.0,1928.0,1314.0,433620.0,374.920868,...,2024-08-28,Tira,1155.564057,Profit,0,0,0,0,0,0
3,TI-CMP-1003,Email,Youth,8.0,31523.000000,3721.0,2088.0,736.0,571872.0,161.130000,...,2024-07-27,Tira,3548.134239,Profit,0,0,1,0,0,0
4,TI-CMP-1004,Paid Ads,Premium Shoppers,15.0,61441.000000,7277.0,3615.0,2602.0,1477936.0,82.070000,...,2024-12-19,Tira,18007.236871,Profit,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166660,NY-CMP-56550,SEO,Youth,16.0,31041.000000,3849.0,1012.0,639.0,162945.0,374.900000,...,2025-02-16,Nykaa,433.635903,Profit,1,0,0,1,0,0
166661,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26.0,27335.000000,3715.0,2184.0,1006.0,792728.0,56.380000,...,2024-11-18,Nykaa,14059.446967,Profit,0,1,0,0,0,0
166662,NY-CMP-56552,Influencer,Tier 2 City Customers,23.0,43481.000000,6447.0,3751.0,1668.0,383640.0,56.180000,...,2024-10-24,Nykaa,6827.764685,Profit,0,0,0,0,0,0
166663,NY-CMP-56553,Social Media,College Students,16.0,55119.386698,2518.0,584.0,299.0,194051.0,227.530000,...,2025-05-22,Nykaa,851.858964,Profit,1,1,0,0,0,0
166664,NY-CMP-56554,Social Media,College Students,25.0,41096.000000,5254.0,2570.0,1894.0,647748.0,35.110000,...,2025-05-30,Nykaa,18448.102820,Profit,0,0,0,1,1,1

In [133]:
final_df['ROI'] = final_df['ROI'].round(2)
final_df['Revenue']=final_df['Revenue'].round(2)

In [134]:
final_df.dtypes

Campaign_ID                    str
Campaign_Type                  str
Target_Audience                str
Duration                   float64
Impressions                float64
Clicks                     float64
Leads                      float64
Conversions                float64
Revenue                    float64
Acquisition_Cost           float64
Language                       str
Engagement_Score           float64
Customer_Segment               str
Date                datetime64[us]
Brand_name                     str
ROI                        float64
Profit_Loss                    str
Email                        int64
Facebook                     int64
Google                       int64
Instagram                    int64
WhatsApp                     int64
YouTube                      int64
dtype: object

In [135]:
final_df['Profit_Loss'].value_counts()

Profit_Loss
Profit    166654
Loss          11
Name: count, dtype: int64

In [136]:
loss_campaign=final_df[final_df['Profit_Loss']=='Loss']

In [137]:
loss_campaign['Campaign_Type'].value_counts()

Campaign_Type
Influencer      4
Paid Ads        3
Social Media    2
Email           2
Name: count, dtype: int64

In [138]:
profit_campaign=final_df[final_df['Profit_Loss']=='Profit']

In [139]:
profit_campaign['Campaign_Type'].value_counts()

Campaign_Type
Influencer      31813
Email           31799
Paid Ads        31601
SEO             31570
Social Media    31513
Name: count, dtype: int64

In [140]:
final_df.describe().round(2)

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,Engagement_Score,Date,ROI,Email,Facebook,Google,Instagram,WhatsApp,YouTube
count,166665.00,166665.00,166665.00,166665.00,166665.00,166665.00,166665.00,166665.00,158566,166665.00,166665.00,166665.00,166665.00,166665.00,166665.00,166665.00
mean,17.49,55068.78,4684.98,1872.17,1028.50,513827.62,376.83,13.76,2024-12-20 17:19:08.841492,6060.48,0.32,0.32,0.32,0.32,0.32,0.32
min,5.00,10001.00,202.00,48.00,17.00,3895.00,8.18,2.56,2024-07-01 00:00:00,-0.74,0.00,0.00,0.00,0.00,0.00,0.00
25%,11.00,33783.00,2185.00,809.00,417.00,185436.00,111.10,8.65,2024-09-25 00:00:00,472.36,0.00,0.00,0.00,0.00,0.00,0.00
50%,17.49,55081.25,4140.00,1564.00,823.00,383520.00,222.92,13.76,2024-12-21 00:00:00,1710.74,0.00,0.00,0.00,0.00,0.00,0.00
75%,24.00,76427.00,6510.00,2525.00,1357.00,659505.00,410.92,18.53,2025-03-17 00:00:00,5630.41,1.00,1.00,1.00,1.00,1.00,1.00
max,30.00,100000.00,14944.00,8876.00,6686.00,4579910.00,15473.16,30.99,2025-06-24 00:00:00,494114.40,1.00,1.00,1.00,1.00,1.00,1.00
std,7.31,25313.05,3097.97,1395.13,836.85,475291.13,523.40,6.17,NaN,13761.33,0.47,0.47,0.47,0.47,0.47,0.47

In [141]:
loss_rows = final_df[(final_df['Profit_Loss'] == 'Loss')]
loss_rows

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,...,Date,Brand_name,ROI,Profit_Loss,Email,Facebook,Google,Instagram,WhatsApp,YouTube
11004,TI-CMP-12004,Social Media,Youth,18.0,55005.698421,422.0,84.0,25.000000,9425.0,9616.32,...,2025-04-08,Tira,-0.02,Loss,0,0,0,0,0,1
19738,TI-CMP-20738,Influencer,Premium Shoppers,6.0,11146.000000,316.0,71.0,22.000000,6072.0,12723.55,...,2025-02-08,Tira,-0.52,Loss,1,0,0,1,1,0
28039,TI-CMP-29039,Email,Premium Shoppers,6.0,10616.000000,274.0,62.0,19.000000,3895.0,15038.00,...,2024-11-15,Tira,-0.74,Loss,1,0,0,0,0,0
55201,NaN,Email,Youth,14.0,12741.000000,261.0,59.0,17.000000,6987.0,14802.41,...,2024-08-17,Tira,-0.53,Loss,0,0,0,0,0,0
63822,PU-CMP-9267,Influencer,Youth,27.0,11035.000000,277.0,72.0,21.000000,9702.0,12109.05,...,2024-12-01,Purplle,-0.20,Loss,0,0,0,1,0,0
74057,PU-CMP-19502,Influencer,Youth,12.0,10078.000000,212.0,48.0,23.000000,9315.0,9978.26,...,2025-02-22,Purplle,-0.07,Loss,0,1,0,0,1,1
79319,PU-CMP-24764,Influencer,Tier 2 City Customers,17.0,10922.000000,249.0,113.0,35.000000,7350.0,7850.57,...,2025-04-16,Purplle,-0.06,Loss,0,0,0,0,0,0
102838,PU-CMP-48283,Social Media,Working Women,13.0,11029.000000,226.0,76.0,27.000000,10422.0,10960.59,...,2024-11-10,Purplle,-0.05,Loss,0,1,0,0,1,0
126693,NY-CMP-16583,Paid Ads,Premium Shoppers,26.0,12268.000000,282.0,64.0,20.000000,8920.0,12423.65,...,NaT,Nykaa,-0.28,Loss,0,0,1,1,0,0
134516,NY-CMP-24406,Paid Ads,Premium Shoppers,5.0,11625.000000,269.0,90.0,27.000000,6183.0,6805.56,...,2024-11-20,Nykaa,-0.09,Loss,0,1,0,0,0,1
144434,NY-CMP-34324,Paid Ads,Youth,27.0,10686.000000,260.0,61.0,1033.357239,14079.0,15473.16,...,2024-10-13,Nykaa,-0.09,Loss,0,0,0,1,0,0

In [142]:
loss_rows = final_df[
    (final_df['Impressions'] >11000) &
    (final_df['Profit_Loss'] == 'Loss')
]

loss_rows

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,...,Date,Brand_name,ROI,Profit_Loss,Email,Facebook,Google,Instagram,WhatsApp,YouTube
11004,TI-CMP-12004,Social Media,Youth,18.0,55005.698421,422.0,84.0,25.0,9425.0,9616.32,...,2025-04-08,Tira,-0.02,Loss,0,0,0,0,0,1
19738,TI-CMP-20738,Influencer,Premium Shoppers,6.0,11146.000000,316.0,71.0,22.0,6072.0,12723.55,...,2025-02-08,Tira,-0.52,Loss,1,0,0,1,1,0
55201,NaN,Email,Youth,14.0,12741.000000,261.0,59.0,17.0,6987.0,14802.41,...,2024-08-17,Tira,-0.53,Loss,0,0,0,0,0,0
63822,PU-CMP-9267,Influencer,Youth,27.0,11035.000000,277.0,72.0,21.0,9702.0,12109.05,...,2024-12-01,Purplle,-0.20,Loss,0,0,0,1,0,0
102838,PU-CMP-48283,Social Media,Working Women,13.0,11029.000000,226.0,76.0,27.0,10422.0,10960.59,...,2024-11-10,Purplle,-0.05,Loss,0,1,0,0,1,0
126693,NY-CMP-16583,Paid Ads,Premium Shoppers,26.0,12268.000000,282.0,64.0,20.0,8920.0,12423.65,...,NaT,Nykaa,-0.28,Loss,0,0,1,1,0,0
134516,NY-CMP-24406,Paid Ads,Premium Shoppers,5.0,11625.000000,269.0,90.0,27.0,6183.0,6805.56,...,2024-11-20,Nykaa,-0.09,Loss,0,1,0,0,0,1

In [143]:
profit_rows = final_df[
    (final_df['Impressions'] <15000) &
    (final_df['Profit_Loss'] == 'Profit')
]

profit_rows

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,...,Date,Brand_name,ROI,Profit_Loss,Email,Facebook,Google,Instagram,WhatsApp,YouTube
70,TI-CMP-1070,SEO,Premium Shoppers,20.0,13123.0,738.000000,151.0,107.0,69443.0,1920.63,...,2024-10-03,Tira,35.16,Profit,1,0,1,0,0,1
90,TI-CMP-1090,Influencer,Working Women,20.0,14253.0,1970.000000,611.0,290.0,156310.0,947.86,...,2024-07-15,Tira,163.91,Profit,0,0,1,1,1,0
105,TI-CMP-1105,SEO,Premium Shoppers,12.0,12913.0,287.000000,131.0,77.0,24486.0,2647.38,...,2024-07-23,Tira,8.25,Profit,0,0,0,0,0,1
108,TI-CMP-1108,SEO,Premium Shoppers,11.0,12090.0,1314.000000,499.0,251.0,74045.0,546.96,...,2024-08-31,Tira,134.38,Profit,1,0,1,0,0,1
146,TI-CMP-1146,Influencer,Premium Shoppers,26.0,12133.0,528.000000,228.0,88.0,52008.0,2711.36,...,2024-11-03,Tira,18.18,Profit,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166593,NY-CMP-56483,Social Media,Youth,10.0,14714.0,1255.000000,690.0,374.0,281622.0,152.25,...,2025-02-12,Nykaa,1848.73,Profit,0,0,1,0,0,1
166595,NY-CMP-56485,Paid Ads,College Students,19.0,14331.0,2014.000000,942.0,651.0,277326.0,123.45,...,2025-01-23,Nykaa,2245.46,Profit,0,0,1,0,1,1
166638,NY-CMP-56528,Influencer,Youth,25.0,10189.0,1229.000000,449.0,268.0,128640.0,397.30,...,2024-11-04,Nykaa,322.79,Profit,0,0,0,1,0,0
166640,NY-CMP-56530,Influencer,Tier 2 City Customers,11.0,13958.0,4690.636879,775.0,466.0,341578.0,368.16,...,2025-02-19,Nykaa,926.80,Profit,1,0,0,1,0,0
166641,NY-CMP-56531,Influencer,Tier 2 City Customers,25.0,12471.0,1326.000000,266.0,154.0,66682.0,1827.54,...,2024-08-28,Nykaa,35.49,Profit,0,1,0,0,1,1

In [144]:
final_df.dtypes

Campaign_ID                    str
Campaign_Type                  str
Target_Audience                str
Duration                   float64
Impressions                float64
Clicks                     float64
Leads                      float64
Conversions                float64
Revenue                    float64
Acquisition_Cost           float64
Language                       str
Engagement_Score           float64
Customer_Segment               str
Date                datetime64[us]
Brand_name                     str
ROI                        float64
Profit_Loss                    str
Email                        int64
Facebook                     int64
Google                       int64
Instagram                    int64
WhatsApp                     int64
YouTube                      int64
dtype: object

In [145]:
final_df[
    (final_df['Impressions'] == 0) &
    (final_df['Clicks'] > 0)
].shape

(0, 23)

In [146]:
final_df.groupby('Campaign_Type')['Revenue'].mean().sort_values()

Campaign_Type
SEO             510040.332821
Influencer      511410.040228
Social Media    514807.638486
Email           514813.896574
Paid Ads        517506.436972
Name: Revenue, dtype: float64

In [147]:
final_df.groupby('Customer_Segment')['Revenue'].mean()

Customer_Segment
College Students         513412.760386
Premium Shoppers         509938.582859
Tier 2 City Customers    515620.488217
Working Women            516686.493917
Youth                    513755.696475
Name: Revenue, dtype: float64

In [148]:
final_df.groupby('Language')['Revenue'].mean()

Language
Bengali    511251.404903
English    513974.140930
Hindi      515243.303904
Tamil      515877.176602
Name: Revenue, dtype: float64

In [149]:
final_df[['Impressions','Clicks','Leads','Conversions',
          'Engagement_Score','Revenue']].corr()

,Impressions,Clicks,Leads,Conversions,Engagement_Score,Revenue
Impressions,1.000000,0.661396,0.589254,0.540782,0.002374,0.474061
Clicks,0.661396,1.000000,0.846538,0.776857,0.594878,0.680866
Leads,0.589254,0.846538,1.000000,0.874596,0.633467,0.767485
Conversions,0.540782,0.776857,0.874596,1.000000,0.611270,0.835317
Engagement_Score,0.002374,0.594878,0.633467,0.611270,1.000000,0.536624
Revenue,0.474061,0.680866,0.767485,0.835317,0.536624,1.000000

In [150]:
final_df[final_df["Revenue"] < 0]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, Language, Engagement_Score, Customer_Segment, Date, Brand_name, ROI, Profit_Loss, Email, Facebook, Google, Instagram, WhatsApp, YouTube]
Index: []

[0 rows x 23 columns]

In [151]:
final_df["Revenue"].describe().round(2)

count     166665.00
mean      513827.62
std       475291.13
min         3895.00
25%       185436.00
50%       383520.00
75%       659505.00
max      4579910.00
Name: Revenue, dtype: float64

In [152]:
final_df[['Impressions', 'Clicks', 'Leads', 'Conversions',
    'Acquisition_Cost', 'Engagement_Score', 'Revenue']].isna().sum()

Impressions         0
Clicks              0
Leads               0
Conversions         0
Acquisition_Cost    0
Engagement_Score    0
Revenue             0
dtype: int64

In [153]:
final_df[['Impressions', 'Clicks', 'Leads', 'Conversions',
    'Acquisition_Cost', 'Engagement_Score', 'Revenue']].describe().round(2)

,Impressions,Clicks,Leads,Conversions,Acquisition_Cost,Engagement_Score,Revenue
count,166665.00,166665.00,166665.00,166665.00,166665.00,166665.00,166665.00
mean,55068.78,4684.98,1872.17,1028.50,376.83,13.76,513827.62
std,25313.05,3097.97,1395.13,836.85,523.40,6.17,475291.13
min,10001.00,202.00,48.00,17.00,8.18,2.56,3895.00
25%,33783.00,2185.00,809.00,417.00,111.10,8.65,185436.00
50%,55081.25,4140.00,1564.00,823.00,222.92,13.76,383520.00
75%,76427.00,6510.00,2525.00,1357.00,410.92,18.53,659505.00
max,100000.00,14944.00,8876.00,6686.00,15473.16,30.99,4579910.00

In [154]:
final_df['Log_Acquisition_Cost'] = np.log1p(final_df['Acquisition_Cost'])
final_df['Log_Revenue'] = np.log1p(final_df['Revenue'])

In [155]:
final_df[['Acquisition_Cost', 'Log_Acquisition_Cost',
    'Revenue', 'Log_Revenue']].describe().round(2)

       Acquisition_Cost  Log_Acquisition_Cost     Revenue  Log_Revenue
count         166665.00             166665.00   166665.00    166665.00
mean             376.83                  5.42   513827.62        12.75
std              523.40                  0.99   475291.13         0.95
min                8.18                  2.22     3895.00         8.27
25%              111.10                  4.72   185436.00        12.13
50%              222.92                  5.41   383520.00        12.86
75%              410.92                  6.02   659505.00        13.40
max            15473.16                  9.65  4579910.00        15.34

In [156]:
final_df[['Acquisition_Cost', 'Revenue',
    'Log_Acquisition_Cost', 'Log_Revenue','Duration']].corr()

,Acquisition_Cost,Revenue,Log_Acquisition_Cost,Log_Revenue,Duration
Acquisition_Cost,1.000000,-0.386215,0.763554,-0.626150,-0.000505
Revenue,-0.386215,1.000000,-0.641856,0.849246,-0.000214
Log_Acquisition_Cost,0.763554,-0.641856,1.000000,-0.762644,0.002820
Log_Revenue,-0.626150,0.849246,-0.762644,1.000000,-0.003418
Duration,-0.000505,-0.000214,0.002820,-0.003418,1.000000

In [157]:
final_df.dtypes

Campaign_ID                        str
Campaign_Type                      str
Target_Audience                    str
Duration                       float64
Impressions                    float64
Clicks                         float64
Leads                          float64
Conversions                    float64
Revenue                        float64
Acquisition_Cost               float64
Language                           str
Engagement_Score               float64
Customer_Segment                   str
Date                    datetime64[us]
Brand_name                         str
ROI                            float64
Profit_Loss                        str
Email                            int64
Facebook                         int64
Google                           int64
Instagram                        int64
WhatsApp                         int64
YouTube                          int64
Log_Acquisition_Cost           float64
Log_Revenue                    float64
dtype: object

In [158]:
print(type(pd))

<class 'module'>

In [159]:
final_df = pd.get_dummies(
    final_df,
    columns=[
        'Campaign_Type',
        'Target_Audience',
        'Language',
        'Customer_Segment'
    ],
    drop_first=True,
    dtype=int
)

In [160]:
final_df.dtypes

Campaign_ID                                          str
Duration                                         float64
Impressions                                      float64
Clicks                                           float64
Leads                                            float64
Conversions                                      float64
Revenue                                          float64
Acquisition_Cost                                 float64
Engagement_Score                                 float64
Date                                      datetime64[us]
Brand_name                                           str
ROI                                              float64
Profit_Loss                                          str
Email                                              int64
Facebook                                           int64
Google                                             int64
Instagram                                          int64
WhatsApp                                           int64
YouTube                                            int64
Log_Acquisition_Cost                             float64
Log_Revenue                                      float64
Campaign_Type_Influencer                           int64
Campaign_Type_Paid Ads                             int64
Campaign_Type_SEO                                  int64
Campaign_Type_Social Media                         int64
Target_Audience_Premium Shoppers                   int64
Target_Audience_Tier 2 City Customers              int64
Target_Audience_Working Women                      int64
Target_Audience_Youth                              int64
Language_English                                   int64
Language_Hindi                                     int64
Language_Tamil                                     int64
Customer_Segment_Premium Shoppers                  int64
Customer_Segment_Tier 2 City Customers             int64
Customer_Segment_Working Women                     int64
Customer_Segment_Youth                             int64
dtype: object

In [161]:
df_copy=final_df.copy()

In [162]:
final_df.columns

Index(['Campaign_ID', 'Duration', 'Impressions', 'Clicks', 'Leads',
       'Conversions', 'Revenue', 'Acquisition_Cost', 'Engagement_Score',
       'Date', 'Brand_name', 'ROI', 'Profit_Loss', 'Email', 'Facebook',
       'Google', 'Instagram', 'WhatsApp', 'YouTube', 'Log_Acquisition_Cost',
       'Log_Revenue', 'Campaign_Type_Influencer', 'Campaign_Type_Paid Ads',
       'Campaign_Type_SEO', 'Campaign_Type_Social Media',
       'Target_Audience_Premium Shoppers',
       'Target_Audience_Tier 2 City Customers',
       'Target_Audience_Working Women', 'Target_Audience_Youth',
       'Language_English', 'Language_Hindi', 'Language_Tamil',
       'Customer_Segment_Premium Shoppers',
       'Customer_Segment_Tier 2 City Customers',
       'Customer_Segment_Working Women', 'Customer_Segment_Youth'],
      dtype='str')

In [ ]:
X = final_df.drop(columns=[
    'Campaign_ID',
    'Date',
    'Brand_name',
    'Revenue',
    'Log_Acquisition_Cost',
    'Log_Revenue',
    'Profit_Loss'
])

y = final_df['Revenue']

In [164]:
X.to_csv("X.csv", index=False)

In [165]:
y

0          222768.0
1          199168.0
2          433620.0
3          571872.0
4         1477936.0
            ...
166660     162945.0
166661     792728.0
166662     383640.0
166663     194051.0
166664     647748.0
Name: Revenue, Length: 166665, dtype: float64

In [166]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [167]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [168]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

MAE_lin= mean_absolute_error(y_test, y_pred)
MSE_lin=mean_squared_error(y_test, y_pred)
RMSE_lin=np.sqrt(mean_squared_error(y_test, y_pred))
R2_Score_lin=r2_score(y_test, y_pred)
Train_Score_lin=model.score(X_train, y_train)
Test_Score_lin=model.score(X_test, y_test)

print("MAE:", MAE_lin)
print("MSE:", MSE_lin)
print("RMSE:", RMSE_lin)
print("R2 Score:", R2_Score_lin)
print("Train Score:", Train_Score_lin)
print("Test Score:", Test_Score_lin)

MAE: 169713.3240574191
MSE: 64976050640.48871
RMSE: 254904.00279416703
R2 Score: 0.7053736513779894
Train Score: 0.703730735750129
Test Score: 0.7053736513779894

In [169]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

#print("R2:", r2_score(y_test, y_pred_rf))
mae_rf_reg = mean_absolute_error(y_test, y_pred_rf)
mse_rf_reg= mean_squared_error(y_test, y_pred_rf)
rmse_rf_reg = np.sqrt(mse_rf_reg)
r2_rf_reg= r2_score(y_test, y_pred_rf)

print("MAE :", mae_rf_reg)
print("MSE :", mse_rf_reg)
print("RMSE:", rmse_rf_reg)
print("R²  :", r2_rf_reg)

import joblib

joblib.dump(model, "roi_model.pkl")

MAE : 164047.64218703684
MSE : 60613944753.715324
RMSE: 246198.99421751365
R²  : 0.7251531134575417

['roi_model.pkl']

In [170]:
print(final_df[['Revenue', 'Conversions', 'Leads', 'Clicks',
                'Impressions', 'Acquisition_Cost']].describe().round(2))

          Revenue  Conversions      Leads     Clicks  Impressions  \
count   166665.00    166665.00  166665.00  166665.00    166665.00
mean    513827.62      1028.50    1872.17    4684.98     55068.78
std     475291.13       836.85    1395.13    3097.97     25313.05
min       3895.00        17.00      48.00     202.00     10001.00
25%     185436.00       417.00     809.00    2185.00     33783.00
50%     383520.00       823.00    1564.00    4140.00     55081.25
75%     659505.00      1357.00    2525.00    6510.00     76427.00
max    4579910.00      6686.00    8876.00   14944.00    100000.00

       Acquisition_Cost
count         166665.00
mean             376.83
std              523.40
min                8.18
25%              111.10
50%              222.92
75%              410.92
max            15473.16

In [171]:
corr = final_df.corr(numeric_only=True)

corr['Revenue'].sort_values(ascending=False)

Revenue                                   1.000000
Log_Revenue                               0.849246
Conversions                               0.835317
Leads                                     0.767485
ROI                                       0.758040
Clicks                                    0.680866
Engagement_Score                          0.536624
Impressions                               0.474061
Email                                     0.004638
Instagram                                 0.004403
Campaign_Type_Paid Ads                    0.003744
Customer_Segment_Working Women            0.002917
Language_Tamil                            0.002407
Customer_Segment_Tier 2 City Customers    0.001821
Language_Hindi                            0.001666
Campaign_Type_Social Media                0.000996
Target_Audience_Premium Shoppers          0.000591
Target_Audience_Tier 2 City Customers     0.000359
Language_English                          0.000172
Facebook                                  0.000059
Customer_Segment_Youth                   -0.000074
Duration                                 -0.000214
Target_Audience_Youth                    -0.000630
WhatsApp                                 -0.000731
Target_Audience_Working Women            -0.001246
Google                                   -0.001308
Campaign_Type_Influencer                 -0.002471
YouTube                                  -0.002880
Campaign_Type_SEO                        -0.003852
Customer_Segment_Premium Shoppers        -0.003948
Acquisition_Cost                         -0.386215
Log_Acquisition_Cost                     -0.641856
Name: Revenue, dtype: float64

In [172]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(
    max_depth=10,
    random_state=42
)

dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
#print("Train R2:", dt.score(X_train, y_train))
#print("Test R2:", dt.score(X_test, y_test))
mae_dt_reg = mean_absolute_error(y_test, y_pred)
mse_dt_reg= mean_squared_error(y_test, y_pred)
rmse_dt_reg = np.sqrt(mse_dt_reg)
r2_dt_reg= r2_score(y_test, y_pred)

print("MAE :", mae_dt_reg)
print("MSE :", mse_dt_reg)
print("RMSE:", rmse_dt_reg)
print("R²  :", r2_dt_reg)

MAE : 167812.0316063631
MSE : 67051958377.6091
RMSE: 258943.9290224992
R²  : 0.6959606890536396

In [173]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=2)

X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

model = LinearRegression()
model.fit(X_train_poly, y_train)
y_pred_poly = model.predict(X_test_poly)

#print(model.score(X_test_poly, y_test))
mae = mean_absolute_error(y_test, y_pred_poly)
mse = mean_squared_error(y_test, y_pred_poly)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 172217.67390253244
MSE : 64964279750.80039
RMSE: 254880.9128805066
R²  : 0.6959606890536396

In [189]:

y = df_copy["Profit_Loss"]

# Features
x = df_copy.drop(columns=[
    "Profit_Loss",
    "ROI",
    "Revenue",
    "Campaign_ID",
    "Date",
    "Brand_name",
    "Log_Acquisition_Cost",
    "Log_Revenue"
])
x.to_csv("profit_loss_X.csv", index=False)

In [175]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [188]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf_classifier.fit(X_train, y_train)
y_pred = rf_classifier.predict(X_test)

joblib.dump(rf_classifier, "profit_model.pkl")

['profit_model.pkl']

In [177]:
print(y.value_counts())
print(y.value_counts(normalize=True) * 100)

Profit_Loss
Profit    166654
Loss          11
Name: count, dtype: int64
Profit_Loss
Profit    99.9934
Loss       0.0066
Name: proportion, dtype: float64

In [178]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label="Profit")
recall = recall_score(y_test, y_pred, pos_label="Profit")
f1 = f1_score(y_test, y_pred, pos_label="Profit")

# Print results
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-Score :", f1)

Accuracy : 0.999939999399994
Precision: 0.999969997899853
Recall   : 0.999969997899853
F1-Score : 0.999969997899853

In [179]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        Loss       0.50      0.50      0.50         2
      Profit       1.00      1.00      1.00     33331

    accuracy                           1.00     33333
   macro avg       0.75      0.75      0.75     33333
weighted avg       1.00      1.00      1.00     33333

In [180]:
df_copy[["Revenue", "Acquisition_Cost", "ROI", "Profit_Loss"]].head(20)

      Revenue  Acquisition_Cost       ROI Profit_Loss
0    222768.0        129.720000   1716.30      Profit
1    199168.0        316.360000    628.56      Profit
2    433620.0        374.920868   1155.56      Profit
3    571872.0        161.130000   3548.13      Profit
4   1477936.0         82.070000  18007.24      Profit
5    185668.0        194.210000    955.02      Profit
6   2691144.0         32.980000  81598.27      Profit
7   1230558.0        374.920868   3281.18      Profit
8    804784.0         43.890000  18335.39      Profit
9    890704.0        190.580000   4672.65      Profit
10   893282.0        128.340000   6959.28      Profit
11   221906.0        269.070000    823.71      Profit
12   876512.0        122.460000   7156.54      Profit
13   132069.0        351.540000    374.69      Profit
14   210166.0        442.950000    473.47      Profit
15    99552.0       1973.180000     49.45      Profit
16   737010.0        114.640000   6427.91      Profit
17   344655.0        181.100000   1902.12      Profit
18   318045.0         71.560000   4443.45      Profit
19   322090.0        374.920868    858.09      Profit

In [181]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

In [182]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy_log = accuracy_score(y_test, y_pred_log)
precision_log = precision_score(y_test, y_pred_log, pos_label="Profit")
recall_log = recall_score(y_test, y_pred_log, pos_label="Profit")
f1_log = f1_score(y_test, y_pred_log, pos_label="Profit")

print("Logistic Regression")
print("-------------------")
print(f"Accuracy : {accuracy_log:.4f}")
print(f"Precision: {precision_log:.4f}")
print(f"Recall   : {recall_log:.4f}")
print(f"F1-Score : {f1_log:.4f}")

Logistic Regression
-------------------
Accuracy : 0.9998
Precision: 1.0000
Recall   : 0.9998
F1-Score : 0.9999

In [183]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    random_state=42,
    class_weight="balanced"
)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

In [184]:
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, pos_label="Profit")
recall_dt = recall_score(y_test, y_pred_dt, pos_label="Profit")
f1_dt = f1_score(y_test, y_pred_dt, pos_label="Profit")

print("Decision Tree")
print("-------------")
print(f"Accuracy : {accuracy_dt:.4f}")
print(f"Precision: {precision_dt:.4f}")
print(f"Recall   : {recall_dt:.4f}")
print(f"F1-Score : {f1_dt:.4f}")

Decision Tree
-------------
Accuracy : 0.9999
Precision: 0.9999
Recall   : 1.0000
F1-Score : 1.0000

In [185]:
print("Random Forest")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-Score : {f1:.4f}")

print("\nLogistic Regression")
print(f"Accuracy : {accuracy_log:.4f}")
print(f"Precision: {precision_log:.4f}")
print(f"Recall   : {recall_log:.4f}")
print(f"F1-Score : {f1_log:.4f}")

print("\nDecision Tree")
print(f"Accuracy : {accuracy_dt:.4f}")
print(f"Precision: {precision_dt:.4f}")
print(f"Recall   : {recall_dt:.4f}")
print(f"F1-Score : {f1_dt:.4f}")

Random Forest
Accuracy : 0.9999
Precision: 1.0000
Recall   : 1.0000
F1-Score : 1.0000

Logistic Regression
Accuracy : 0.9998
Precision: 1.0000
Recall   : 0.9998
F1-Score : 0.9999

Decision Tree
Accuracy : 0.9999
Precision: 0.9999
Recall   : 1.0000
F1-Score : 1.0000

In [186]:
df_all['Campaign_Type'].value_counts()

Campaign_Type
Influencer      31817
Email           31801
Paid Ads        31604
SEO             31570
Social Media    31515
Name: count, dtype: int64

In [187]:
df_all["Channel_Used"].value_counts()

Channel_Used
Email                           8953
Instagram                       8858
Facebook                        8791
Google                          8740
WhatsApp                        8705
                                ...
Google, YouTube, Email           398
Email, YouTube, Instagram        390
Instagram, Facebook, YouTube     390
Email, Google, YouTube           390
Email, YouTube, Facebook         389
Name: count, Length: 156, dtype: int64